apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "deploy.st4sd.ibm.com/v1alpha1",
          "kind": "SimulationToolkit",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "olm",
              "app.kubernetes.io/instance": "simulationtoolkit-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simulationtoolkit",
              "app.kubernetes.io/part-of": "olm"
            },
            "name": "simulationtoolkit-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2022-12-31T14:08:15Z"
    operators.operatorframework.io/builder: operator-sdk-v1.26.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: st4sd-olm-deploy.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SimulationToolkit is the Schema for the simulation-toolkits API
      displayName: Simulation Toolkit
      kind: SimulationToolkit
      name: simulation-toolkits.deploy.st4sd.ibm.com
      version: v1alpha1
  description: The Simulation Toolkit for Scientific Discovery (ST4SD) simplifies
    the development, execution and dissemination of virtual experiments by providing
    powerful querying capabilities, robust and multi-environment execution support,
    AI acceleration capabilities, and a global showcase.
  displayName: Simulation Toolkit For Scientific Discovery (ST4SD)
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - security.openshift.io
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
          resources:
          - securitycontextconstraints
        - apiGroups:
          - authorization.openshift.io
          - rbac.authorization.k8s.io
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
          resources:
          - clusterrolebindings
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - deploy.st4sd.ibm.com
          resources:
          - simulation-toolkits
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - deploy.st4sd.ibm.com
          resources:
          - simulation-toolkits/finalizers
          verbs:
          - update
        - apiGroups:
          - deploy.st4sd.ibm.com
          resources:
          - simulation-toolkits/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        #### this is the equivalent to system:auth-delegator
        #### we need it for openshift/oauth-proxy
        - verbs:
            - create
          apiGroups:
            - authentication.k8s.io
          resources:
            - tokenreviews
        - verbs:
            - create
          apiGroups:
            - authorization.k8s.io
          resources:
            - subjectaccessreviews
        serviceAccountName: st4sd-olm-deploy-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: st4sd-olm-deploy
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: olm
          control-plane: controller-manager
        name: st4sd-olm-deploy
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/st4sd/st4sd-olm-deploy:latest
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 1000m
                    memory: 512Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: st4sd-olm-deploy-manager
              terminationGracePeriodSeconds: 10
      #### VV: "permissions" contents must go under "clusterPermissions"
      # We need the operator to be able to deploy ST4SD *in any namespace*.
      # Therefore, the operator needs to be able to deploy all the below objects
      # in *any* namespace.
      permissions:
      - rules:
        #### role-workflow-user.yaml
        - apiGroups:
          - ""
          resources:
            # VV: we can optionally check whether users have access to services living in this
            # namespace before we let them access the st4sd microservices
            - services
          verbs: ["get", "list", "watch"]

        # VV: Workflow users may need to work with Job objects because flow creates 1 Job per component Task
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
          - deletecollection

        - apiGroups:
          - batch
          resources:
          - jobs/status
          verbs:
          - get
          - list
          - watch

        # VV: Workflow users may interact with pods (e.g. oc debug, oc exec etc)
        - apiGroups:
          - ""
          resources:
            - pods
            # VV: we can optionally check whether users have access to services living in this
            # namespace before we let them access the st4sd microservices
            - services
            # VV: We don't need these ones below for deploying but having them around makes it that
            # much easier to troubleshoot the workflow stack
            - pods/attach
            - pods/exec
          verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

        - apiGroups:
          - ""
          resources:
            - pods/log
          verbs: ["get", "list", "watch"]

        # VV: Users may end up creating/managing Workflow and Dataset objects
        - apiGroups:
          # VV: This is the old ApiGroup it's deprecated and will be removed
          - hpsys.ie.ibm.com
          - st4sd.ibm.com
          - com.ie.ibm.hpsys
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - watch
          - patch
        #### role-stack-deploy.yaml
        # VV: Permission to read current namespace and object
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get

        - apiGroups:
          - ""
          - project.openshift.io
          resources:
          - projects
          verbs:
          - get
        # VV: Permissions required to deploy helm updates
        - apiGroups:
            - rbac.authorization.k8s.io
            - authorization.openshift.io
          resources:
            - roles
            - rolebindings
          verbs:  ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

        # VV: Like above, but for persistentvolumeclaims instead
        - apiGroups:
            - ""
          verbs: ["list", "watch", "get"]
          resources: 
            - persistentvolumeclaims

        # VV: We use deploymentConfigs for the various parts of the stack
        - apiGroups:
            - apps.openshift.io
          resources:
            - deploymentconfigs
          verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

        # VV: DeploymentConfigs also calls for the ability to create imagestreams, and run "oc import-image"
        - apiGroups:
            - image.openshift.io
          resources:
            - imagestreams
          verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

        - apiGroups:
            - image.openshift.io
          resources:
            - imagestreamimports
          verbs: ["create"]

        # VV: We also create a couple of OpenShift routes to expose services that we spin up
        - apiGroups:
            - route.openshift.io
          resources:
            - routes
          verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

        # VV: We also create a couple of OpenShift routes to expose services that we spin up
        - apiGroups:
            - route.openshift.io
          resources:
            - routes/custom-host
          verbs: ["create"]

        # VV: We don't use deployments now but may end up using them in the future
        - apiGroups:
            - apps
          resources:
            - deployments
          verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

        # VV: Required to launch and manage Jobs in the namespace
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

        # VV: This is for common k8s objects such as pods, sa, secrets, etc
        - apiGroups:
          - ""
          resources:
            - replicationcontrollers
            - serviceaccounts
            - configmaps
            - endpoints
            - pods
            - secrets
            # VV: we can optionally check whether users have access to services living in this
            # namespace before we let them access the st4sd microservices
            - services
            # VV: We don't need these ones below for deploying but having them around makes it that 
            # much easier to troubleshoot the workflow stack
            - pods/attach
            - pods/exec
          verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

        - apiGroups:
          - ""
          resources:
            - events
          verbs: ["create", "get", "list", "patch", "watch"]

        - apiGroups:
          - ""
          resources:
            - pods/log
          verbs: ["get", "list", "watch"]

        # VV: This is for creating/managing Workflow and Dataset objects
        - apiGroups:
            # VV: This is the old ApiGroup it's deprecated and will be removed
          - hpsys.ie.ibm.com
          - st4sd.ibm.com
          - com.ie.ibm.hpsys
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - watch
          - update 
        #### role-authenticate-microservices.yaml
        - apiGroups:
          - ""
          resources:
            - services
          verbs: ["get", "list", "watch"]
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        #### default
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: st4sd-olm-deploy-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - simulations
  - hpc
  - high-performance
  - surrogates
  links:
  - name: st4sd-olm-deploy
    url: https://st4sd.github.io/overview
  maintainers:
  - email: vassilis.vassiliadis@ibm.com
    name: Vassilis Vassiliadis
  maturity: alpha
  provider:
    name: IBM Research, Europe - Dublin
    url: st4sd.github.io/overview
  version: 0.0.2
