---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.st4sd.ibm.com
  resources:
  - st4sdruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.st4sd.ibm.com
  resources:
  - st4sdruntimes/finalizers
  verbs:
  - update
- apiGroups:
  - core.st4sd.ibm.com
  resources:
  - st4sdruntimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - deploy.st4sd.ibm.com
  resources:
  - simulationtoolkits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.st4sd.ibm.com
  resources:
  - simulationtoolkits/finalizers
  verbs:
  - update
- apiGroups:
  - deploy.st4sd.ibm.com
  resources:
  - simulationtoolkits/status
  verbs:
  - get
  - patch
  - update
