---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - deploy.st4sd.res.ibm.com
  resources:
  - simulation-toolkits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.st4sd.res.ibm.com
  resources:
  - simulation-toolkits/finalizers
  verbs:
  - update
- apiGroups:
  - deploy.st4sd.res.ibm.com
  resources:
  - simulation-toolkits/status
  verbs:
  - get
  - patch
  - update
