apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: olm.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SimulationToolkit is the Schema for the simulation-toolkits API
      displayName: Simulation Toolkit
      kind: SimulationToolkit
      name: simulation-toolkits.deploy.st4sd.res.ibm.com
      version: v1alpha1
  description: The Simulation Toolkit for Scientific Discovery (ST4SD) simplifies
    the development, execution and dissemination of virtual experiments by providing
    powerful querying capabilities, robust and multi-environment execution support,
    AI acceleration capabilities, and a global showcase.
  displayName: Simulation Toolkit For Scientific Discovery (ST4SD)
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - simulations
  - hpc
  - high-performance
  - surrogates
  links:
  - name: Olm
    url: https://olm.domain
  maintainers:
  - email: vassilis.vassiliadis@ibm.com
    name: Vassilis Vassiliadis
  maturity: alpha
  provider:
    name: IBM Research, Europe - Dublin
    url: st4sd.github.io/overview
  version: 0.0.0
