kind: SimulationToolkit
apiVersion: deploy.st4sd.ibm.com/v1alpha1
metadata:
  name: my-st4sd
  namespace: my-namespace
spec:
  setup:
    # If running on OpenShift, ${CLUSTER_INGRESS} expands to the ingress of the cluster
    # Make sure that the routeDomain you pick is available on the cluster. 
    # For example, there should be NO other route on the cluster (in any namespace) with 
    # the same domain.
    routeDomain: my-st4sd.${CLUSTER_INGRESS}
    datastoreIdentifier: st4sd

    # Make sure that these PersistentVolumeClaim (PVC) objects exist in the same namespace
    # See the README.md instructions for more information.
    pvcDatastore: datastore-mongodb
    pvcInstances: workflow-instances-pvc
    pvcRuntimeService: runtime-service
