apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: st4sd-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/st4sd/official-base/st4sd-olm-catalog:latest
  displayName: Catalog of ST4SD images
  publisher: ST4SD
  updateStrategy:
    registryPoll:
      interval: 15m

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: st4sd
  namespace: openshift-marketplace
spec:
  selector:
    matchLabels:
      st4sd.ibm.com/runtime-deploy: "true"
